backend:
  name: github
  repo: tinkerhub/TinkerHub-Learning-Paths
  branch: main
  squash_merges: true
  open_authoring: true
publish_mode: editorial_workflow
media_folder: static/images
public_folder: images
logo_url: https://paths.tinkerhub.org/logo.png
editor:
  preview: false
collections:
  - name: 'learningpath'
    label: 'Learning Paths'
    label_singular: 'Learning Path'
    description: 'Create or update TinkerHub Learning Paths'
    folder: 'content'
    filter: { field: "mainpage", value: false }
    create: true
    delete: false
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Publish Date", name: "date", widget: "datetime", required: true }
      - { label: "Short Description",
          name: "shortDescription",
          pattern: ['.{0,100}', "Short description should be less than 100 characters"],
          widget: "string",
          required: false }
      - { label: "Category", name: "category", widget: "select", required: true, options: [
          "language","framework", "devops", "ai-ml", "other" ] }
      - { label: "Image", name: "image", widget: "image", required: true }
      - { label: "Tags List (Comma separated)", name: "tags", widget: "list", allow_add: true, required: true }
      - { label: "Authors (Comma separated Github username list)", name: "authors", widget: "list", allow_add: true, required: true }
      - label: "Path Type"
        name: "pathType"
        widget: "select"
        required: false
        multiple: true
        options:
          - frontend
          - backend
          - fullstack
          - nativeApps
          - crossPlatform
          - gcp
          - azure
          - aws
          - linux
          - python
          - go
          - dbAndNetworking
          - docker
          - kubernetes
          - architect
          - engineer
          - developer
          - security
          - networking
          - ai
          - arAndVr
          - blockchain
          - iot
          - roboticsAndAutonmation
          - unity
          - unreal
          - blender
          - autodeskMaya
          - csharp
          - cpp
          - javascript
      - { label: "mainpage", name: "mainpage", widget: "hidden", default: false }
      - { label: "draft", name: "draft", widget: "hidden", default: false }
      - { label: "Body", name: "body", widget: "markdown", required: true }
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "mainpage", name: "mainpage", widget: "hidden", default: true }
          - { label: "draft", name: "draft", widget: "hidden", default: false }
          - { label: "Intro", name: "body", widget: "markdown", required: true }
          - { label: "Join Us URL", name: "joinURL", widget: "string", required: true }
          - { label: "Join Button Text", name: "joinText", widget: "string", required: true }
          - { label: "Intro Title", name: "introTitle", widget: "string", required: true }
